name: Python trial

on: [push]

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run test
        run: |
           pytest

      
      # - name: Test with pytest
      #   run: |
      #     # Install pytest and the coverage tool.
      #     pip install pytest pytest-cov
      #     # Run the tests and generate a Junit and coverage reports.
      #     pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      
      # - name: Install Ruff
      #   run: pip install ruff

      
      # - name: Lint code with Ruff
      #   run: ruff check --output-format=github --target-version=py39
       

     
      # - name: Check code formatting with Ruff
      #   run: ruff format --diff --target-version=py39
      #   continue-on-error: true

      - name: Install pylint
        run: pip install pylint

      - name: Lint code with pylint
        run: pylint --output-format=github .
  # Pylint infers the Python version from the environment it's running in.
  # The '.' means Pylint will check all Python files in the current directory.

      - name: Check code formatting with pylint
        run: pylint --output-format=github --score=n .
        continue-on-error: true

          

      
          

        

      
    
    




